In [44]:



import pandas as pd
import numpy as np

In [45]:
df = pd.DataFrame(np.array([[0,0,0],[0,1,1],[1,0,1],[1,1,0]]),columns=['x1','x2','label'])

In [46]:
df

x1  x2  label
0   0   0      0
1   0   1      1
2   1   0      1
3   1   1      0

In [47]:
W = np.random.rand(2,1)
W


array([[0.99738277],
       [0.52883812]])

In [48]:
b= np.random.rand()
b

0.13933344295684325

In [49]:
x=np.array(df[['x1','x2']])
y=np.array(df['label'])
x=x.T
x,y
x.shape


(2, 4)

In [50]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [51]:
from sklearn.metrics import log_loss
J = log_loss(y,A)

In [55]:


alpha = 0.01
for i in range (100):
    Z =np.dot(W.T,x)+b
    A = sigmoid(Z)
    A = np.where(A < 0.5, 0, 1)
    A = A.squeeze()
    
    J = log_loss(y,A)
    print(J)
    
    dz = A - y
    dz.shape
    dz = np.expand_dims(dz,axis = 0)
    dw =  np.dot(x,dz.T)/x.shape[0]
    db = np.sum(dz,axis =1)/x.shape[0]
    W = W - alpha * dw
    b = b - alpha * db
    



17.269388197455342
17.26978799617044
17.269388197455342
17.26978799617044
17.269388197455342
17.26978799617044
17.269388197455342
17.26978799617044
17.269388197455342
17.26978799617044
17.269388197455342
17.26978799617044
17.269388197455342
17.26978799617044
17.269388197455342
17.26978799617044
17.269388197455342
17.26978799617044
17.269388197455342
17.26978799617044
17.269388197455342
17.26978799617044
17.269388197455342
17.26978799617044
17.269388197455342
17.26978799617044
17.269388197455342
17.26978799617044
17.269388197455342
17.26978799617044
17.269388197455342
17.26978799617044
17.269388197455342
17.26978799617044
17.269388197455342
17.26978799617044
17.269388197455342
17.26978799617044
17.269388197455342
17.26978799617044
17.269388197455342
17.26978799617044
17.269388197455342
17.26978799617044
17.269388197455342
17.26978799617044
17.269388197455342
17.26978799617044
17.269388197455342
17.26978799617044
17.269388197455342
17.26978799617044
17.269388197455342
17.26978799617044
1

In [63]:
from sklearn.metrics import confusion_matrix
a=confusion_matrix(y,A)
a

array([[0, 2],
       [0, 2]], dtype=int64)

In [64]:
y

array([0, 1, 1, 0])

In [61]:
A

array([1, 1, 1, 1])